apiVesrion: app/v1
kind: Deployment

metadta:
  name: nginx-deployment

spec: 
  replicas: 1

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        server: nginx
    spec: 
      container: 
        - name: nginx
          image: app-nginx:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80

