apiVesrion: app/v1
kind: Deployment

metadta:
  name: {{ .Values.nginx.name }}-deployment

spec: 
  replicas: {{ .Values.nginx.replicas }}

  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}

  template:
    metadata:
      labels:
        server: {{ .Values.nginx.name }}
    spec: 
      container: 
        - name: {{ .Values.nginx.name }}
          image: {{ .Values.nginx.image.name }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.nginx.image.exposedPort }}

