apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.nginx.name }}-loadbalancer-service

spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app: {{ .Values.nginx.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.nginx.image.exposedPorts }}
