apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.userservice.name }}-cluster-service

spec:
  type: {{ .Values.userservice.service.type }}
  selector:
    app: {{ .Values.userservice.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.userservice.image.exposedPort }}
