apiVesrion: app/v1
kind: Deployment

metadta:
  name: userservice-deployment

spec: 
  replicas: 2

  selector:
    matchLabels:
      app: userservice

  template:
    metadata:
      labels:
        server: userservice
    spec: 
      container: 
        - name: userservice
          image: userservice:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env: 
            - name: NODE_ENV
              value: production

